name: money_manager
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^3.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_route: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  hive_generator: ^1.0.1
  json_serializable: ^6.2.0
  auto_route_generator: ^5.0.1

flutter:
  uses-material-design: true
